def sports():
    data = [
        ('futbol', 'Fútbol', 'La energía de jugar en equipo', 'Comparte la cancha, mejora tu resistencia y encuentra tu lugar en el equipo.', 'resistencia,social,salud', 120, 60, 'Balón, zapatillas para la superficie, canilleras y ropa deportiva.', 'Empieza con pases y control de balón. Practica con un grupo de nivel similar y aumenta el tiempo de juego gradualmente.', 'Planifica una comida habitual antes del partido, lleva agua y repón líquidos durante las pausas.', 'Cancha habilitada y superficie en buen estado. Coordina compañeros y verifica las reglas del lugar.', 'exterior', 'intermedia', 'Coordinación, resistencia y trabajo en equipo.'),
        ('natacion', 'Natación', 'Encuentra tu ritmo en el agua', 'Una práctica de cuerpo completo para trabajar la técnica y la resistencia.', 'resistencia,salud', 260, 45, 'Traje de baño, gorro, gafas y sandalias para el recinto.', 'Empieza con un instructor y en una piscina supervisada. Aprende respiración y flotación antes de aumentar distancias.', 'Mantén comidas regulares y lleva agua aunque entrenes en piscina. Ajusta los horarios de alimentación a tu comodidad.', 'Piscina habilitada con supervisión y acceso a vestidores. Revisa horarios y normas del recinto.', 'interior', 'intermedia', 'Coordinación, resistencia y movilidad.'),
        ('baloncesto', 'Baloncesto', 'Cada pase abre una oportunidad', 'Movimiento, estrategia y coordinación para disfrutar dentro de la cancha.', 'social,resistencia', 140, 60, 'Balón, zapatillas con buen agarre y ropa cómoda.', 'Practica el bote y los pases antes de jugar partidos. Aprende a aterrizar y a cambiar de dirección con control.', 'Acompaña tus comidas con variedad de alimentos y lleva agua a los entrenamientos. Aprovecha las pausas para hidratarte.', 'Cancha con aros seguros y suelo sin obstáculos. Puede practicarse en recintos cerrados o al aire libre.', 'ambos', 'intermedia', 'Agilidad, coordinación y cooperación.'),
        ('tenis', 'Tenis', 'Un nuevo desafío en cada punto', 'Desarrolla precisión, concentración y movimiento a tu propio ritmo.', 'coordinacion,resistencia', 380, 60, 'Raqueta, pelotas y zapatillas adecuadas a la cancha.', 'Comienza con golpes suaves y ejercicios de control. Aprende la técnica con apoyo de un instructor y descansa entre sesiones.', 'Lleva agua y organiza tus comidas según el horario del partido. Para jornadas largas, prevé alimentos habituales que toleres bien.', 'Cancha con red y superficie cuidada. Reserva un horario y coordina con un compañero o instructor.', 'ambos', 'alta', 'Concentración, precisión y agilidad.'),
        ('voleibol', 'Voleibol', 'Conecta con tu equipo', 'Una disciplina para compartir, coordinar y mejorar con cada jugada.', 'social,coordinacion', 80, 50, 'Balón, zapatillas deportivas y rodilleras opcionales.', 'Empieza por la recepción y el pase. Practica las posiciones y aprende a caer y desplazarte con control.', 'Mantén una alimentación variada y organiza pausas de hidratación. Lleva agua para toda la sesión.', 'Cancha despejada con red bien instalada y espacio de seguridad alrededor.', 'ambos', 'basica', 'Coordinación, reflejos y trabajo en equipo.'),
    ]
    result = []
    for identifier, name, title, desc, goal, cost, minutes, equipment, tips, food, conditions, space, level, benefits in data:
        result.append(dict(id=identifier, nombre=name, descripcion=title + '. ' + desc,
                           objetivo=goal, costo=cost, moneda='BOB', periodo='mes', minutos=minutes,
                           equipamiento=equipment, consejos=tips, alimentacion=food,
                           condiciones=conditions, espacio=space, dificultad=level,
                           beneficios=benefits, imagen='/static/photos/' + identifier + '.jpg', activo=True))
    return result
