create table if not exists public.deportes_axel (
    identificador text primary key check (identificador ~ '^[a-z0-9-]{1,80}$'),
    nombre text not null check (char_length(trim(nombre)) between 1 and 100),
    costo_estimado numeric(10,2) check (costo_estimado >= 0),
    moneda text not null default 'BOB' check (moneda ~ '^[A-Z]{3}$'),
    periodo_costo text not null default '' check (char_length(periodo_costo) <= 100),
    equipamiento text not null default '' check (char_length(equipamiento) <= 3000),
    tiempo_practica text not null default '' check (char_length(tiempo_practica) <= 3000),
    alimentacion text not null default '' check (char_length(alimentacion) <= 3000),
    recomendaciones text not null default '' check (char_length(recomendaciones) <= 3000),
    condiciones text not null default '' check (char_length(condiciones) <= 3000),
    espacio_practica text check (espacio_practica in ('interior', 'exterior', 'ambos')),
    instalaciones_especiales text check (instalaciones_especiales in ('si', 'no')),
    requiere_companeros text check (requiere_companeros in ('si', 'no')),
    imagen_ruta text,
    check (costo_estimado is null or char_length(trim(periodo_costo)) > 0)
);

insert into public.deportes_axel (identificador, nombre)
values ('futbol', 'Fútbol'), ('baloncesto', 'Baloncesto'),
       ('natacion', 'Natación'), ('tenis', 'Tenis')
on conflict (identificador) do nothing;

create table if not exists public.reportes_hu4 (
    id bigint generated by default as identity primary key,
    deporte text not null,
    campo_observado text not null,
    descripcion text not null check (char_length(trim(descripcion)) between 1 and 1000),
    estado text not null default 'pendiente' check (estado in ('pendiente', 'revisado')),
    fecha_creacion timestamptz not null default now(),
    fecha_revision timestamptz
);

alter table public.deportes_axel enable row level security;
alter table public.reportes_hu4 enable row level security;
revoke all on table public.deportes_axel, public.reportes_hu4 from anon, authenticated;
grant select, insert, update on table public.deportes_axel, public.reportes_hu4 to service_role;
grant usage, select on sequence public.reportes_hu4_id_seq to service_role;
create index if not exists reportes_hu4_estado_fecha_idx
    on public.reportes_hu4 (estado, fecha_creacion desc, id desc);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('imagenes-deportes-axel', 'imagenes-deportes-axel', true, 5242880,
        array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do nothing;
